###
#create GET request in bookshop service document
GET http://localhost:4004/odata/v4/book-shop/

###
#create GET request in bookshop metadata
GET http://localhost:4004/odata/v4/book-shop/$metadata

###
#create GET request in book service (query)
GET http://localhost:4004/odata/v4/book-shop/Book

###
#create GET request in book service (read)
GET http://localhost:4004/odata/v4/book-shop/Book(1)
# HTTP/1.1 200 OK
# HTTP/1.1 404 Not Found

###
#create POST request in book service
POST http://localhost:4004/odata/v4/book-shop/Book
Content-Type: application/json

{
    "ID": 2,
    "title": "Book #02"
}
#HTTP/1.1 201 Created
#HTTP/1.1 400 Bad Request